table 'Discount Bands'
	lineageTag: 7ef0812d-8a3c-497e-a780-74e99905ea04

	column 'Discount Band'
		dataType: string
		lineageTag: 36180cd9-32fa-43ec-8314-51fed0a066d6
		summarizeBy: none
		sourceColumn: Discount Band
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: cfb86966-1711-4c25-a401-906d901d5670
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'Discount Bands' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8svPS1XSUTJQitWJVvLJLweyDcFs39SUzNJcINcIzPXITM8AcoyVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Discount Band" = _t, Index = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Discount Band", type text}, {"Index", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

