table superstore
	lineageTag: ea3545c0-8e2a-4799-87c0-0fe6a4654f90

	column 'Customer.ID'
		dataType: string
		isHidden
		lineageTag: 451224ca-fda5-4fca-9f5e-34a495899d47
		summarizeBy: none
		sourceColumn: Customer.ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0
		lineageTag: 4e1fe509-4030-4d37-8963-220cd41b4767
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Order.ID'
		dataType: string
		lineageTag: 9605c5ae-0dca-40ec-b93d-69c0e620635a
		summarizeBy: none
		sourceColumn: Order.ID

		annotation SummarizationSetBy = Automatic

	column 'Product.ID'
		dataType: string
		isHidden
		lineageTag: 7e82962c-537d-4f50-b112-e55a691d0a96
		summarizeBy: none
		sourceColumn: Product.ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		lineageTag: d15bdcb5-27f7-4ee2-92de-878a130793b1
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: d3afdf67-5034-4c22-b6fe-d6678af10b45
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: int64
		formatString: 0
		lineageTag: 85995c3c-8c38-4fb6-97fd-56a313f2107d
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

	column 'Shipping.Cost'
		dataType: double
		lineageTag: 7cf7c7ce-46cd-4270-bc94-85bc772c2220
		summarizeBy: sum
		sourceColumn: Shipping.Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4e6cc284-4062-4119-91a0-626b126242f8
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column weeknum
		dataType: int64
		formatString: 0
		lineageTag: c24d93c0-5422-4b14-8582-f4c512a88258
		summarizeBy: sum
		sourceColumn: weeknum

		annotation SummarizationSetBy = Automatic

	column 'Order.Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48ea78b3-e56b-42c8-b34d-cae64eef21bc
		summarizeBy: none
		sourceColumn: Order.Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship.Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 207146f8-fb0f-4520-87a6-ad041068a0bd
		summarizeBy: none
		sourceColumn: Ship.Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Discount Value'
		dataType: double
		lineageTag: 9280c60c-5d2e-4885-9335-fe6bc654f457
		summarizeBy: sum
		sourceColumn: Discount Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Band'
		dataType: string
		lineageTag: b0111ce6-a299-4b47-bcfd-65f7427f866c
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: double
		lineageTag: 7f10fab5-f96d-4876-91eb-116d2748322b
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales'
		dataType: double
		lineageTag: ed7c07ad-8466-4722-bd5a-291bffc51529
		summarizeBy: sum
		sourceColumn: Net Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order.Priority_key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d0d95e28-3a97-4bd3-9d98-efe21d2cf00c
		summarizeBy: none
		sourceColumn: Order.Priority_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ship.Mode_key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f1a5d023-9d7d-4ce3-adea-5d952ac35193
		summarizeBy: none
		sourceColumn: Ship.Mode_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1aaeb14-b96f-4a9a-ba5f-ffc5fd634636
		summarizeBy: none
		sourceColumn: Location_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition superstore = m
		mode: import
		source = ```
				let
				  Source = superstore_source,
				  #"Replaced Market Values" = Table.ReplaceValue(
				    Source,
				    "Africa",
				    "EMEA",
				    Replacer.ReplaceValue,
				    {"Market"}
				  ),
				  #"Added Discount Value" = Table.AddColumn(
				    #"Replaced Market Values",
				    "Discount Value",
				    each [Gross Sales] * [Discount],
				    type number
				  ),
				  #"Added Net Sales" = Table.AddColumn(
				    #"Added Discount Value",
				    "Net Sales",
				    each [Gross Sales] * (1 - [Discount]),
				    type number
				  ),
				  #"Added COGS Column" = Table.AddColumn(
				    #"Added Net Sales",
				    "COGS",
				    each [Gross Sales] - [Profit],
				    type number
				  ),
				  #"Reordered Columns" = Table.ReorderColumns(
				    #"Added COGS Column",
				    {
				      "Category",
				      "City",
				      "Country",
				      "Customer.ID",
				      "Customer.Name",
				      "Discount",
				      "Market",
				      "Order.Date",
				      "Order.ID",
				      "Order.Priority",
				      "Product.ID",
				      "Product.Name",
				      "Profit",
				      "Quantity",
				      "Region",      
				      "Gross Sales",
				      "COGS",
				      "Segment",
				      "Ship.Date",
				      "Ship.Mode",
				      "Shipping.Cost",
				      "State",
				      "Sub.Category",
				      "Year",
				      "Market Fullname",
				      "weeknum"
				    }
				  ),
				    #"Merged Order Priority" = Table.NestedJoin(#"Reordered Columns", {"Order.Priority"}, OrderPriority, {"Order.Priority"}, "OrderPriority", JoinKind.LeftOuter),
				    #"Expanded OrderPriority" = Table.ExpandTableColumn(#"Merged Order Priority", "OrderPriority", {"Order.Priority_key"}, {"Order.Priority_key"}),
				    #"Removed Order Priority" = Table.RemoveColumns(#"Expanded OrderPriority",{"Order.Priority", "Product.Name"}),
				    #"Merged Ship Mode" = Table.NestedJoin(#"Removed Order Priority", {"Ship.Mode"}, ShipMode, {"Ship.Mode"}, "ShipMode", JoinKind.LeftOuter),
				    #"Expanded ShipMode" = Table.ExpandTableColumn(#"Merged Ship Mode", "ShipMode", {"Ship.Mode_key"}, {"Ship.Mode_key"}),
				    #"Removed Ship Mode" = Table.RemoveColumns(#"Expanded ShipMode",{"Ship.Mode"}),
				    #"Merged Location" = Table.NestedJoin(#"Removed Ship Mode", {"City", "Country", "Region", "State"}, Location, {"City", "Country", "Region", "State"}, "Location", JoinKind.LeftOuter),
				    #"Expanded Location" = Table.ExpandTableColumn(#"Merged Location", "Location", {"Location_key"}, {"Location_key"}),
				    #"Removed Location Columns & Customer Name" = Table.RemoveColumns(#"Expanded Location",{"City", "Country", "Market", "Region", "State", "Market Fullname", "Customer.Name", "Category", "Segment", "Sub.Category"})
				in
				    #"Removed Location Columns & Customer Name"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

